/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/echoInput": {
    /** returns back exactly what it is sent. */
    post: operations["echoInput"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description An error occurred in the call */
    ApiError: {
      message?: string;
    };
  };
  responses: {
    /** @description The specified resource was not found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["ApiError"];
      };
    };
    /** @description An unexpected error has occurred in the server. */
    ServerError: {
      content: {
        "application/json": components["schemas"]["ApiError"];
      };
    };
  };
  parameters: {
    /** @description A parameter that makes the function behave differently depending on what is sent. */
    mock?: "fail" | "not_found";
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** returns back exactly what it is sent. */
  echoInput: {
    parameters: {
      query?: {
        mock?: components["parameters"]["mock"];
      };
    };
    /** @description The input to the operation */
    requestBody?: {
      content: {
        "application/json": {
          input: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            response: string;
          };
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
}
